name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Clean Maven cache to prevent conflicts
      - name: Clean Maven Cache
        run: mvn dependency:purge-local-repository

      # Restore Maven dependencies
      - name: Restore Maven Dependencies
        run: mvn dependency:resolve

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify