name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Clean Maven cache to prevent конфлікти
      - name: Clean Maven Cache
        run: mvn dependency:purge-local-repository

      # Встановлення залежностей Maven
      - name: Restore Maven Dependencies
        run: mvn dependency:resolve

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify